-- Generated by Oracle SQL Developer Data Modeler 19.2.0.182.1216
--   at:        2020-05-12 21:22:21 AEST
--   site:      Oracle Database 11g
--   type:      Oracle Database 11g
-- Author: Arie Hendrikse
-- Assignment 1B. Monash Art Union.

-- Drop tables added to redo spool output
drop table sale;
drop table exhibit;
drop table movement;
drop table artwork;

drop table customer;

drop table gallery;
drop table artist;
drop table style;

commit;
set echo on
spool mau_schema_output.txt

-- Generated by Oracle SQL Developer Data Modeler 19.2.0.182.1216
--   at:        2020-05-13 11:01:27 AEST
--   site:      Oracle Database 11g
--   type:      Oracle Database 11g



CREATE TABLE artist (
    artist_code       NUMBER(4) NOT NULL,
    artist_fname      VARCHAR2(50 CHAR) NOT NULL,
    artist_lname      VARCHAR2(50 CHAR) NOT NULL,
    artist_no_works   NUMBER(3) NOT NULL,
    artist_street     VARCHAR2(50 CHAR) NOT NULL,
    artist_town       VARCHAR2(50 CHAR) NOT NULL,
    artist_state      VARCHAR2(3 CHAR) NOT NULL,
    artist_ph         NUMBER(11) NOT NULL
);

ALTER TABLE artist ADD CHECK ( artist_code > 999 );

COMMENT ON COLUMN artist.artist_code IS
    'artist code';

COMMENT ON COLUMN artist.artist_fname IS
    'artist first name';

COMMENT ON COLUMN artist.artist_lname IS
    'artist last name';

COMMENT ON COLUMN artist.artist_no_works IS
    'number of artist artowrks created';

COMMENT ON COLUMN artist.artist_street IS
    'artist street of his address';

COMMENT ON COLUMN artist.artist_town IS
    'town of artist''s address';

COMMENT ON COLUMN artist.artist_state IS
    'the state from the artists address';

COMMENT ON COLUMN artist.artist_ph IS
    'artist phone number';

ALTER TABLE artist ADD CONSTRAINT artist_pk PRIMARY KEY ( artist_code );

CREATE TABLE artwork (
    art_id           NUMBER(4) NOT NULL,
    artist_code      NUMBER(4) NOT NULL,
    art_title        VARCHAR2(50 CHAR) NOT NULL,
    art_min_price    NUMBER(8, 2) NOT NULL,
    art_media_desc   VARCHAR2(500 CHAR),
    style_name       VARCHAR2(50 CHAR) NOT NULL,
    art_date_added   DATE NOT NULL
);

ALTER TABLE artwork ADD CONSTRAINT chk_art_id_pos CHECK ( art_id > 0 );

ALTER TABLE artwork ADD CONSTRAINT chk_min_pos CHECK ( art_min_price > 0 );

COMMENT ON COLUMN artwork.art_id IS
    'artowrk id';

COMMENT ON COLUMN artwork.artist_code IS
    'artist code';

COMMENT ON COLUMN artwork.art_title IS
    'title of the artwork ';

COMMENT ON COLUMN artwork.art_min_price IS
    'minimum sale price of the artwork';

COMMENT ON COLUMN artwork.art_media_desc IS
    'media description of the artwork';

COMMENT ON COLUMN artwork.style_name IS
    'name of the style';

COMMENT ON COLUMN artwork.art_date_added IS
    'Date the artwork was added to the mau';

ALTER TABLE artwork ADD CONSTRAINT artwork_pk PRIMARY KEY ( art_id,
                                                            artist_code );

CREATE TABLE customer (
    cust_id       NUMBER(4) NOT NULL,
    cust_fname    VARCHAR2(50 CHAR) NOT NULL,
    cust_lname    VARCHAR2(50 CHAR) NOT NULL,
    cust_street   VARCHAR2(50 CHAR) NOT NULL,
    cust_town     VARCHAR2(50 CHAR) NOT NULL,
    cust_state    VARCHAR2(3 CHAR) NOT NULL,
    cust_ph       NUMBER(11) NOT NULL
);

ALTER TABLE customer ADD CHECK ( cust_id > 1000 );

COMMENT ON COLUMN customer.cust_id IS
    'customer id';

COMMENT ON COLUMN customer.cust_fname IS
    'customer first name';

COMMENT ON COLUMN customer.cust_lname IS
    'customer last name';

COMMENT ON COLUMN customer.cust_street IS
    'street for customers address';

COMMENT ON COLUMN customer.cust_town IS
    'customer town';

COMMENT ON COLUMN customer.cust_state IS
    'state of customer address';

COMMENT ON COLUMN customer.cust_ph IS
    'customer phone number';

ALTER TABLE customer ADD CONSTRAINT customer_pk PRIMARY KEY ( cust_id );

CREATE TABLE exhibit (
    exh_start_date   DATE NOT NULL,
    exh_end_date     DATE,
    gal_id           NUMBER(4) NOT NULL,
    art_id           NUMBER(4) NOT NULL,
    artist_code      NUMBER(4) NOT NULL,
    art_feat         VARCHAR2(3 CHAR) DEFAULT 'No' NOT NULL
);

ALTER TABLE exhibit
    ADD CONSTRAINT deat_bool_check CHECK ( art_feat IN (
        'No',
        'Yes'
    ) );

COMMENT ON COLUMN exhibit.exh_start_date IS
    'start date of exhibit';

COMMENT ON COLUMN exhibit.exh_end_date IS
    'end date of exhibit';

COMMENT ON COLUMN exhibit.gal_id IS
    'gallery id';

COMMENT ON COLUMN exhibit.art_id IS
    'artowrk id';

COMMENT ON COLUMN exhibit.artist_code IS
    'artist code';

COMMENT ON COLUMN exhibit.art_feat IS
    'featured in catalog (yes/no)';

ALTER TABLE exhibit
    ADD CONSTRAINT exhibit_pk PRIMARY KEY ( gal_id,
                                            art_id,
                                            artist_code );

CREATE TABLE gallery (
    gal_id          NUMBER(4) NOT NULL,
    gal_name        VARCHAR2(50 CHAR) NOT NULL,
    gal_manager     VARCHAR2(50 CHAR) NOT NULL,
    gal_state       VARCHAR2(3 CHAR) NOT NULL,
    gal_town        VARCHAR2(50 CHAR) NOT NULL,
    gal_street      VARCHAR2(50 CHAR) NOT NULL,
    gal_commision   NUMBER(3) NOT NULL,
    gal_phone       NUMBER(11) NOT NULL,
    gal_opens       DATE,
    gal_closes      DATE
);

ALTER TABLE gallery ADD CONSTRAINT chk_gal_id_pos CHECK ( gal_id > 0 );

COMMENT ON COLUMN gallery.gal_id IS
    'gallery id';

COMMENT ON COLUMN gallery.gal_name IS
    'gallery name';

COMMENT ON COLUMN gallery.gal_manager IS
    'the manager of the gallery';

COMMENT ON COLUMN gallery.gal_state IS
    'state the gallery is located in';

COMMENT ON COLUMN gallery.gal_town IS
    'town the gallery is located in';

COMMENT ON COLUMN gallery.gal_street IS
    'street address the gallery is located on';

COMMENT ON COLUMN gallery.gal_commision IS
    'percentage of commision the gallery takes';

COMMENT ON COLUMN gallery.gal_phone IS
    'gallery phone number';

COMMENT ON COLUMN gallery.gal_opens IS
    'time the gallery opens';

COMMENT ON COLUMN gallery.gal_closes IS
    'time the gallery close ';

ALTER TABLE gallery ADD CONSTRAINT gallery_pk PRIMARY KEY ( gal_id );

CREATE TABLE movement (
    move_date     DATE NOT NULL,
    art_status    VARCHAR2(280 CHAR) NOT NULL,
    art_id        NUMBER(4) NOT NULL,
    artist_code   NUMBER(4) NOT NULL,
    gal_id        NUMBER(4)
);

COMMENT ON COLUMN movement.move_date IS
    'movement date ';

COMMENT ON COLUMN movement.art_status IS
    'The status of the item';

COMMENT ON COLUMN movement.art_id IS
    'artowrk id';

COMMENT ON COLUMN movement.artist_code IS
    'artist code';

COMMENT ON COLUMN movement.gal_id IS
    'gallery id';

ALTER TABLE movement
    ADD CONSTRAINT movement_pk PRIMARY KEY ( move_date,
                                             art_id,
                                             artist_code );

CREATE TABLE sale (
    sale_id       NUMBER(8) NOT NULL,
    sale_date     DATE NOT NULL,
    sale_price    NUMBER(8, 2) NOT NULL,
    cust_id       NUMBER(4) NOT NULL,
    gal_id        NUMBER(4) NOT NULL,
    art_id        NUMBER(4) NOT NULL,
    artist_code   NUMBER(4) NOT NULL
);

ALTER TABLE sale ADD CONSTRAINT chk_sale_id_len CHECK ( sale_id > 999999 );

COMMENT ON COLUMN sale.sale_id IS
    'sale id';

COMMENT ON COLUMN sale.sale_date IS
    'date of the sale';

COMMENT ON COLUMN sale.sale_price IS
    'price of the sale in dollars';

COMMENT ON COLUMN sale.cust_id IS
    'customer id';

COMMENT ON COLUMN sale.gal_id IS
    'gallery id';

COMMENT ON COLUMN sale.art_id IS
    'artowrk id';

COMMENT ON COLUMN sale.artist_code IS
    'artist code';

CREATE UNIQUE INDEX sale__idx ON
    sale (
        gal_id
    ASC,
        art_id
    ASC,
        artist_code
    ASC );

ALTER TABLE sale ADD CONSTRAINT sale_pk PRIMARY KEY ( sale_id );

CREATE TABLE style (
    style_name    VARCHAR2(50 CHAR) NOT NULL,
    style_name1   VARCHAR2(50 CHAR)
);

COMMENT ON COLUMN style.style_name IS
    'name of the style';

COMMENT ON COLUMN style.style_name1 IS
    'name of the style';

ALTER TABLE style ADD CONSTRAINT style_pk PRIMARY KEY ( style_name );

ALTER TABLE artwork
    ADD CONSTRAINT artwork_artist_fk FOREIGN KEY ( artist_code )
        REFERENCES artist ( artist_code );

ALTER TABLE artwork
    ADD CONSTRAINT artwork_style_fk FOREIGN KEY ( style_name )
        REFERENCES style ( style_name );

ALTER TABLE exhibit
    ADD CONSTRAINT exhibit_artwork_fk FOREIGN KEY ( art_id,
                                                    artist_code )
        REFERENCES artwork ( art_id,
                             artist_code )
            ON DELETE CASCADE;

ALTER TABLE exhibit
    ADD CONSTRAINT exhibit_gallery_fk FOREIGN KEY ( gal_id )
        REFERENCES gallery ( gal_id )
            ON DELETE CASCADE;

ALTER TABLE movement
    ADD CONSTRAINT movement_artwork_fk FOREIGN KEY ( art_id,
                                                     artist_code )
        REFERENCES artwork ( art_id,
                             artist_code );

ALTER TABLE movement
    ADD CONSTRAINT movement_gallery_fk FOREIGN KEY ( gal_id )
        REFERENCES gallery ( gal_id )
            ON DELETE SET NULL;

ALTER TABLE sale
    ADD CONSTRAINT sale_customer_fk FOREIGN KEY ( cust_id )
        REFERENCES customer ( cust_id );

ALTER TABLE sale
    ADD CONSTRAINT sale_exhibit_fk FOREIGN KEY ( gal_id,
                                                 art_id,
                                                 artist_code )
        REFERENCES exhibit ( gal_id,
                             art_id,
                             artist_code );

ALTER TABLE style
    ADD CONSTRAINT style_style_fk FOREIGN KEY ( style_name1 )
        REFERENCES style ( style_name )
            ON DELETE SET NULL;



-- Oracle SQL Developer Data Modeler Summary Report: 
-- 
-- CREATE TABLE                             8
-- CREATE INDEX                             1
-- ALTER TABLE                             24
-- CREATE VIEW                              0
-- ALTER VIEW                               0
-- CREATE PACKAGE                           0
-- CREATE PACKAGE BODY                      0
-- CREATE PROCEDURE                         0
-- CREATE FUNCTION                          0
-- CREATE TRIGGER                           0
-- ALTER TRIGGER                            0
-- CREATE COLLECTION TYPE                   0
-- CREATE STRUCTURED TYPE                   0
-- CREATE STRUCTURED TYPE BODY              0
-- CREATE CLUSTER                           0
-- CREATE CONTEXT                           0
-- CREATE DATABASE                          0
-- CREATE DIMENSION                         0
-- CREATE DIRECTORY                         0
-- CREATE DISK GROUP                        0
-- CREATE ROLE                              0
-- CREATE ROLLBACK SEGMENT                  0
-- CREATE SEQUENCE                          0
-- CREATE MATERIALIZED VIEW                 0
-- CREATE MATERIALIZED VIEW LOG             0
-- CREATE SYNONYM                           0
-- CREATE TABLESPACE                        0
-- CREATE USER                              0
-- 
-- DROP TABLESPACE                          0
-- DROP DATABASE                            0
-- 
-- REDACTION POLICY                         0
-- 
-- ORDS DROP SCHEMA                         0
-- ORDS ENABLE SCHEMA                       0
-- ORDS ENABLE OBJECT                       0
-- 
-- ERRORS                                   0
-- WARNINGS                                 0


commit;
spool off
set echo off

