-- Generated by Oracle SQL Developer Data Modeler 19.2.0.182.1216
--   at:        2020-05-04 13:50:35 AEST
--   site:      Oracle Database 12c
--   type:      Oracle Database 12c

--student id: 12345678
--student name: Firstname Lastname
-- Capture run of script in file called custorders_schema_output.txt
set echo on
SPOOL custorders_schema_output.txt

CREATE TABLE maintenance (
    maint_cost             NUMBER(8),
    maint_datetime         DATE NOT NULL,
    maint_desc             VARCHAR2 
--  ERROR: VARCHAR2 size not specified 
     NOT NULL,
    pay_no                 NUMBER(8),
    prop_no                NUMBER(8) NOT NULL,
    rent_lease_startdate   DATE NOT NULL
);

COMMENT ON COLUMN maintenance.maint_cost IS
    'maintenance cost';

COMMENT ON COLUMN maintenance.maint_datetime IS
    'maintenance date and time';

COMMENT ON COLUMN maintenance.maint_desc IS
    'maintenance description';

COMMENT ON COLUMN maintenance.pay_no IS
    'payment number';

COMMENT ON COLUMN maintenance.prop_no IS
    'property number';

COMMENT ON COLUMN maintenance.rent_lease_startdate IS
    'rent lease start date';

CREATE UNIQUE INDEX maintenance__idx ON
    maintenance (
        pay_no
    ASC );

ALTER TABLE maintenance ADD CONSTRAINT maintenance_pk PRIMARY KEY ( prop_no,
                                                                    maint_datetime
                                                                    );

CREATE TABLE owner (
    owner_no        NUMBER(8) NOT NULL,
    owner_title     VARCHAR2(3) NOT NULL,
    owner_givname   VARCHAR2(20) NOT NULL,
    owner_famname   VARCHAR2(20) NOT NULL,
    owner_addr      VARCHAR2(50) NOT NULL
);

COMMENT ON COLUMN owner.owner_no IS
    'owner number';

COMMENT ON COLUMN owner.owner_title IS
    'owner title';

COMMENT ON COLUMN owner.owner_givname IS
    'owner first name';

COMMENT ON COLUMN owner.owner_famname IS
    'owner last name';

COMMENT ON COLUMN owner.owner_addr IS
    'owner_address';

ALTER TABLE owner ADD CONSTRAINT owner_pk PRIMARY KEY ( owner_no );

CREATE TABLE payment (
    pay_no                  NUMBER(8) NOT NULL,
    pay_date                DATE NOT NULL,
    pay_type                VARCHAR2(50 CHAR),
    pay_amount              NUMBER(8, 2) NOT NULL,
    pay_paidby              DATE NOT NULL,
    maint_datetime          DATE,
    rent_lease_startdate2   DATE NOT NULL,
    prop_no1                NUMBER(8) NOT NULL,
    prop_no                 NUMBER(8)
);

COMMENT ON COLUMN payment.pay_no IS
    'payment number';

COMMENT ON COLUMN payment.pay_date IS
    'pay date';

COMMENT ON COLUMN payment.pay_type IS
    'pay type';

COMMENT ON COLUMN payment.pay_amount IS
    'payment amount';

COMMENT ON COLUMN payment.pay_paidby IS
    'payment paid by';

COMMENT ON COLUMN payment.maint_datetime IS
    'maintenance date and time';

COMMENT ON COLUMN payment.rent_lease_startdate2 IS
    'rent lease start date';

COMMENT ON COLUMN payment.prop_no1 IS
    'property number';

COMMENT ON COLUMN payment.prop_no IS
    'property number';

CREATE UNIQUE INDEX payment__idx ON
    payment (
        maint_datetime
    ASC,
        prop_no
    ASC );

ALTER TABLE payment ADD CONSTRAINT payment_pk PRIMARY KEY ( pay_no );

CREATE TABLE property (
    prop_no        NUMBER(8) NOT NULL,
    prop_address   VARCHAR2(50) NOT NULL,
    owner_no       NUMBER(8) NOT NULL
);

COMMENT ON COLUMN property.prop_no IS
    'property number';

COMMENT ON COLUMN property.prop_address IS
    'property address';

COMMENT ON COLUMN property.owner_no IS
    'owner number';

ALTER TABLE property ADD CONSTRAINT property_pk PRIMARY KEY ( prop_no );

CREATE TABLE property_tenant (
    rent_lease_startdate   DATE NOT NULL,
    rent_weekly_rate       NUMBER(8, 2) NOT NULL,
    rent_bond              NUMBER(8, 2) NOT NULL,
    prop_no                NUMBER(8) NOT NULL,
    tenant_no              NUMBER(8) NOT NULL,
    property_tenant_id     NUMBER NOT NULL
);

COMMENT ON COLUMN property_tenant.rent_lease_startdate IS
    'rent lease start date';

COMMENT ON COLUMN property_tenant.rent_weekly_rate IS
    'weekly rent rate';

COMMENT ON COLUMN property_tenant.rent_bond IS
    'rent bond';

COMMENT ON COLUMN property_tenant.prop_no IS
    'property number';

COMMENT ON COLUMN property_tenant.tenant_no IS
    'tenant number';

ALTER TABLE property_tenant ADD CONSTRAINT property_tenant_pkv1 PRIMARY KEY ( property_tenant_id
);

ALTER TABLE property_tenant ADD CONSTRAINT property_tenant_pk UNIQUE ( rent_lease_startdate
,
                                                                       prop_no );

CREATE TABLE tenant (
    tenant_no        NUMBER(8) NOT NULL,
    tenant_title     VARCHAR2(3 CHAR) NOT NULL,
    tenant_givname   VARCHAR2(20 CHAR) NOT NULL,
    tenant_famname   VARCHAR2(20 CHAR) NOT NULL,
    tenant_phone     VARCHAR2(15 CHAR) NOT NULL
);

COMMENT ON COLUMN tenant.tenant_no IS
    'tenant number';

COMMENT ON COLUMN tenant.tenant_title IS
    'tenant title';

COMMENT ON COLUMN tenant.tenant_givname IS
    'tenant given name';

COMMENT ON COLUMN tenant.tenant_famname IS
    'tenant family name';

COMMENT ON COLUMN tenant.tenant_phone IS
    'tenant phone number';

ALTER TABLE tenant ADD CONSTRAINT tenant_pk PRIMARY KEY ( tenant_no );

ALTER TABLE property_tenant
    ADD CONSTRAINT "is" FOREIGN KEY ( prop_no )
        REFERENCES property ( prop_no );

ALTER TABLE property
    ADD CONSTRAINT owns FOREIGN KEY ( owner_no )
        REFERENCES owner ( owner_no );

ALTER TABLE payment
    ADD CONSTRAINT relation_6 FOREIGN KEY ( maint_datetime,
                                            prop_no )
        REFERENCES maintenance ( prop_no,
                                 maint_datetime );

ALTER TABLE maintenance
    ADD CONSTRAINT relation_6v1 FOREIGN KEY ( pay_no )
        REFERENCES payment ( pay_no );

ALTER TABLE property_tenant
    ADD CONSTRAINT relation_7 FOREIGN KEY ( tenant_no )
        REFERENCES tenant ( tenant_no );

ALTER TABLE payment
    ADD CONSTRAINT relation_8 FOREIGN KEY ( rent_lease_startdate2,
                                            prop_no1 )
        REFERENCES property_tenant ( rent_lease_startdate,
                                     prop_no );

ALTER TABLE maintenance
    ADD CONSTRAINT responsibles FOREIGN KEY ( rent_lease_startdate,
                                              prop_no )
        REFERENCES property_tenant ( rent_lease_startdate,
                                     prop_no );

CREATE SEQUENCE property_tenant_property_tenan START WITH 1 NOCACHE ORDER;

CREATE OR REPLACE TRIGGER property_tenant_property_tenan BEFORE
    INSERT ON property_tenant
    FOR EACH ROW
    WHEN ( new.property_tenant_id IS NULL )
BEGIN
    :new.property_tenant_id := property_tenant_property_tenan.nextval;
END;
/


SPOOL off
set echo off
-- Oracle SQL Developer Data Modeler Summary Report: 
-- 
-- CREATE TABLE                             6
-- CREATE INDEX                             2
-- ALTER TABLE                             14
-- CREATE VIEW                              0
-- ALTER VIEW                               0
-- CREATE PACKAGE                           0
-- CREATE PACKAGE BODY                      0
-- CREATE PROCEDURE                         0
-- CREATE FUNCTION                          0
-- CREATE TRIGGER                           1
-- ALTER TRIGGER                            0
-- CREATE COLLECTION TYPE                   0
-- CREATE STRUCTURED TYPE                   0
-- CREATE STRUCTURED TYPE BODY              0
-- CREATE CLUSTER                           0
-- CREATE CONTEXT                           0
-- CREATE DATABASE                          0
-- CREATE DIMENSION                         0
-- CREATE DIRECTORY                         0
-- CREATE DISK GROUP                        0
-- CREATE ROLE                              0
-- CREATE ROLLBACK SEGMENT                  0
-- CREATE SEQUENCE                          1
-- CREATE MATERIALIZED VIEW                 0
-- CREATE MATERIALIZED VIEW LOG             0
-- CREATE SYNONYM                           0
-- CREATE TABLESPACE                        0
-- CREATE USER                              0
-- 
-- DROP TABLESPACE                          0
-- DROP DATABASE                            0
-- 
-- REDACTION POLICY                         0
-- TSDP POLICY                              0
-- 
-- ORDS DROP SCHEMA                         0
-- ORDS ENABLE SCHEMA                       0
-- ORDS ENABLE OBJECT                       0
-- 
-- ERRORS                                   1
-- WARNINGS                                 0
